### PR TITLE
fix(dashboard): hide selected currency in Bitcoin Statistics and Mempool dropdown

### LINKED ISSUE #365: UX Enhancement: Hide or disable selected currency in dropdown in  Bitcoin Statistics Page
**Description**
In the currency selector dropdown, the currently selected currency (e.g., **USD**) still appears as a selectable option. This results in a redundant action and can be slightly confusing from a UX perspective.

Image

**Expected Behavior**

* The selected currency should either:

  * Be **hidden** from the dropdown list, or
  * Be **disabled** to clearly indicate it’s already selected.

**Actual Behavior**

* The selected currency remains visible and clickable in the dropdown.

**Steps to Reproduce**

1. Open the currency selector dropdown
2. Select **USD**
3. Open the dropdown again and observe that **USD** is still listed

**Suggested Solution (Optional)**

* Filter out the currently selected currency from the options list

### PR DESCRIPTION
**Pull request by SHREESHANTH99**
Fixes UX issue where the currently selected currency remains selectable
in the Bitcoin Statistics dropdown.

Updated the dropdown behavior to hide the selected currency from the options list.

Applied the same behavior to the Mempool tab to maintain consistency.

No UI styling changes were introduced as requested.

Fixes #365

### CODE REVIEW

**Review by priyashuu — CHANGES_REQUESTED** [review]
Please fix the failing CI tests. Also, review the Copilot suggestions and implement them if they are valid and align with the project requirements.

**Comment by SHREESHANTH99** [comment]
@priyashuu can you review

File: dashboard/src/components/BitcoinStats/Prices.tsx [hunk 1]
```diff
@@ -168,18 +170,18 @@ const BitcoinPriceTracker: React.FC = () => {
...
-            GBP
-          </option>
-          <option className="bg-gray-500" value="JPY">
-            JPY
-          </option>
+          {CURRENCIES.map((curr) => (
+            <option
+              key={curr}
+              className={
+                curr === currency ? 'bg-gray-500 text-gray-400' : 'bg-gray-500'
```
Comment (priyashuu) [inline dashboard/src/components/BitcoinStats/Prices.tsx]: As you mentioned in the PR description that no UI changes were made, I noticed that you introduced a new text color (text-gray-400). Is this change necessary?

**Review by priyashuu — COMMENTED** [review]
Did you get a chance to test the PR? It doesn’t appear to resolve the issue that was reported.

**Comment by SHREESHANTH99** [comment]
> Did you get a chance to test the PR? It doesn’t appear to resolve the issue that was reported.

Yes, I’ve tested it locally. The currently selected currency is now disabled using the disabled attribute, so it cannot be selected again

**Review by priyashuu — COMMENTED** [review]
Thanks, I’ve tested this PR.

I noticed a UI issue: when a user selects a currency, extra space remains visible in the dropdown area (as shown in the screenshot). Ideally, this space should collapse so the layout looks clean and consistent.

Could you please look into this?

Image

**Comment by SHREESHANTH99** [comment]
@priyashuu can you review now

**Comment by SHREESHANTH99** [comment]
https://github.com/user-attachments/assets/d494d1a4-7285-40db-8809-6226f0b427a6

https://github.com/user-attachments/assets/1cfd00f3-17bb-48cd-9284-75c551fc63cf


@priyashuu can you check ?

**Review by priyashuu — DISMISSED** [review]
LGTM

**Comment by priyashuu** [comment]
Please fix the Prettier CI failed test .

**Comment by SHREESHANTH99** [comment]
@priyashuu is it okay now ?

**Review by priyashuu — APPROVED** [review]
Yes, everything is good now. Thank you for your contribution!
